== Console

=== Automatic login to tty1

[source,bash]
----
sudo systemctl edit getty@tty1
----

Then paste the following

----
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin <username> --noclear %I $TERM
----

=== No access to pty for tool

If a tool (i.e. `screen`) cannot open a pseudo terminal, use

[source,bash]
----
script /dev/null
----
Reason is most probably that the user that owns the pty is not the
current user anymore, like after `su - user`. `script` has the side-effect
of creating a new pseudo terminal `/dev/pts/X`, for the current user with which a later `screen` will not have any problem. `/dev/null` simply means that `script` will not save its typescript output.

_NOTE_: It is not good to alter the file access rights for the dev node
since this would allow access to your terminal.

=== echo, IFS and newline

`SSH` keys need line breaks in text format. If a key is cat'ed into a `bash`
variable, line breaks are still there.
If they are output with

[source,bash]
----
echo $VARIABLE
----

line breaks become spaces. If the internal field separator "IFS" is set to `" "`, line breaks are preserved.

[source,bash]
----
IFSOLD=$IFS
IFS=" "
echo $VARIABLE
IFS=$IFSOLD
----

However, line breaks are also kept when the variable is enclosed with double-ticks.

[source,bash]
----
echo "$VARIABLE"
----

The reason is that without double-ticks, `bash` does not interpret it as a string, so `echo` gets several arguments and prints them separated with spaces. The argument separation is done by `bash`. Another example is to set
`IFS=a`. In this case, if you assign the variable `A=bbbaccc` and use `echo` to print it, you get a space instead of `a`, since `a` is used as field separator. The same works for `for`:

[source,bash]
----
IFSBACK=$IFS
IFS=a
A=bbbaccc
for i in $A
do
	echo $i
done
IFS=$IFSBACK
----

Here `a` effectively becomes a newline.

=== Separate filename with extension from path

[source,bash]
----
bash -c TEST="/usr/share/zoneinfo/zone.tab"; echo "${TEST##*/}"
----
