== Development

=== Versioning

==== Git

===== Merge a branch

Never merge abranch and allow non-fast-forwarding!

Always use:

[source,bash]
----
git merge --ff-only <branch>
----

===== Change merge-commit to normal commit

The only difference between a merge commit and a normal commit is that a
merge commit has two parents. Use

[source,bash]
----
git replace --edit <COMMIT SHA>
----

Afterwards, only the `view` of the commit graph is altered, not the
commits on the branch themselves. To reify this, use

[source,bash]
----
git filter-branch -- --all
----

===== Change author of commit

[source,bash]
----
git rebase -i <SHA to change>
----

Mark commit as `edit`.

Use

[source,bash]
----
git commit --amend --reset-author
----

include::makefile.adoc[]

=== C/C++

==== Vim Autocompletion

To have autocompletion in vim, add to your `.vim.rc`:

[source]
----
Plugin 'ycm-core/YouCompleteMe'
----

between `call vundle#begin(...)` and `vundle#end`.

Also you need one default `.ycm_extra_conf.py`. You can
get that file from `github.com/ycm-core/ycm` and copy it to `.vim`.
Then add the following to your .vim.rc:

[source]
----
let g:ycm_global_ycm_extra_conf = '.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'
----

Compile `you-complete-me` with `--all` option in `<vundleplugs>/YouCompleteMe` (Your <vundelplugs> directory can be set in `.vimrc` as option to `call vundle#begin(<path>)`.

Be sure you also have `clang` installed.

[source,bash],bash]
----
./install.py --all
----

==== Multilib (32-bit on 64-bit system)

To run 32-bit applications on a 64-bit system, one has to install the 32-bit libc and libstdc++.

===== Debian

[source,bash]
----
dpkg --add-architecture i386
apt-get update
apt-get install libc6:i386 libstdc++6:i386
----

===== Arch

Add the following to `/etc/pacman.conf`

[source]
----
[multilib]
Include = /etc/pacman.d/mirrorlist
----

All packages in `multilib` can be listed with

[source,bash]
----
pacman -Sl multilib
----

32-bit libraries begin with `lib32-`. The C library `lib32-glibc` is in the `lib32-gcc-libs` package, which in turn is in the `multilib-devel` group.

To remove all packages installed with multilib, run

[source,bash]
----
pacman -R $(comm -12 <(pacman -Qq | sort) <(pacman -Slq multilib | sort))
----

==== Order of object files in static library

The order does not matter. Just package all object files with

[source,bash]
----
ar rcv output.a file1.o file2.o file3.o
----

This is interesting, because we don't need the dependency file generation by the compiler then.

==== Build kernel

Build it out of tree! From within the build-directory, use

[source,bash]
----
make -C <path-to-source> O=$(pwd) <target>
----

==== autotools

New Project with autotools

* install `autotools`
* install `automake

Create project directory tree. Create source files.

[source,bash]
----
autoscan
----

Rename `configure.scan` to `configure.ac`. Edit `configure.ac`
(`AC_INIT` line).

Write `Makefile.am` (one or more). Edit `configure.ac` and add
`AM_INIT_AUTOMAKE`.

Then in `lib/Makefile.am`:

* If you don’t want to install a lib, use `noinst_LIBRARIES`
* static libs need `RANLIB`, so add `AC_PROG_RANLIB` into the
`configure.ac`
* Do not use `CFLAGS` and `LDFLAGS`, but `AM_CFLAGS` and `AM_LDFLAGS`.

==== Cross-Compilation

Build cross-compiler from `aur` needs the following steps:

* Have native: `elfutils`, `gperf`

Build in the following order:

1.  binutils
2.  gcc-stage1
3.  linux-api-headers
4.  glibc-headers
5.  gcc-stage2 (removes stage1)
6.  glibc (removes glibc-headers)
7.  gcc (removes stage2)

==== gcc `instrument functions` and profiling

Programs with `address randomization` are hard to debug since `addr2line` does not work with these addresses.

Test program `ext.c`:

[source,c,linenums]
----
int B(int a)
{
	return a >> 2;
}
----

Test program `main.c`:

[source,c,linenums]
----
#define _GNU_SOURCE
#include <execinfo.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <link.h>
#include <dlfcn.h>

char *reloc_addr;

extern int B(int x);

int A() {
	printf("This is function A.\n");
	volatile int i = B(8);
}

__attribute__((no_instrument_function))
void __cyg_profile_func_enter(void *this, void *caller)
{
	void *buffer[100];
	char **strings;

	int nptrs = backtrace(buffer, 3);

	strings = backtrace_symbols(buffer, nptrs);
	if (strings == NULL) {
		perror("backtrace_symbols");
		exit(EXIT_FAILURE);
	}

	Dl_info i, j;

	memset(&i,0,sizeof(i));
	memset(&j,0,sizeof(i));
	if (dladdr(caller, &i) != 0);
	if (dladdr(this, &j) != 0);

	printf("instrument: %p <rel: %p> (=%s) called %p <rel: %p> (=%s)\n", caller,
		(char *)caller - reloc_addr,
		i.dli_sname,
		this,
		(char *)this - reloc_addr,
		j.dli_sname);

	if (nptrs == 3) {
		printf("backtrace: %s called %s\n", strings[2], strings[1]);
	}

	free(strings);
}

__attribute__((no_instrument_function))
static int callback(struct dl_phdr_info *info, size_t size, void *data)
{
	int j;
	for (j = 0; j < info->dlpi_phnum; j++) {
		if (info->dlpi_phdr[j].p_type == PT_LOAD) {
			const char *beg = (const char*) info->dlpi_addr + info->dlpi_phdr[j].p_vaddr;
			const char *end = beg + info->dlpi_phdr[j].p_memsz;
			const char *cb = (const char *)&callback;
			if (beg < cb && cb < end) {
				// Found PT_LOAD that "covers" callback().
				printf("ELF header is at %p, image linked at 0x%zx, relocation: 0x%zx\n",
					beg, info->dlpi_phdr[j].p_vaddr, info->dlpi_addr);
				reloc_addr = (char *)info->dlpi_addr;
				return 1;
			}
			return 0;
		}
	}
	return 0;
}

__attribute__((constructor,no_instrument_function))
void initprog() {
	dl_iterate_phdr(callback, NULL);
}

__attribute__((no_instrument_function))
int main(void)
{
	A();
	return 0;
}
----

Compile with

[source,bash]
----
gcc -no-pie -rdynamic -g -pg -finstrument-functions main.c ext.c -ldl -o main
----

Check with

[source,bash]
----
./main
REL_ADDR="$(./main | grep -o "rel:\ 0[x][0-9a-f]\+" | cut -d' ' -f2)" ; for a in $(echo $REL_ADDR); do addr2line -e ./main $a -f; done
----

it should output something like

----
main
/home/projects/Cprofile/main.c:85
A
/home/projects/Cprofile/main.c:14
A
/home/projects/Cprofile/main.c:16
B
/home/projects/Cprofile/ext.c:2
----

=== Python

Interesting modules:

* `Requests` - http lib
* `Scrapy` - webscraping
* `wxPython` - GUI
* `Pillow` - imaging lib
* `SQLAlchemy` - database lib
* `BeautifulSoup` - xml and html parser
* `Twisted` - network app dev
* `NumPy` - Advanced maths
* `SciPy` - algorithms and mathematical tools for science
* `matplotlib` - data plotting
* `Pygame` - 2d game dev
* `Pyglet` - 3d and multimedia framework
* `pyQT` - GUI
* `pyGtk` - GUI
* `Scapy` - packet sniffer and analyzer
* `pywin32` - for windows b’’h
* `nltk` - natural language toolkig
* `nose` - testing framework
* `SymPy` - symbolic maths
* `IPython` - prompt with extras

=== Ruby

==== Local gems for `bundle` and `gem`

You can use the `--path` option to `bundle` for project dependent gems directory, or you
can globally configure a user-gems directory for all user projects:

[source,bash]
----
bundle config path "~/.gem"
----

[[asciidoc_ruby]]
===== asciidoctor-pdf

[source,bash]
----
bundle init
cat <<EOF > Gemfile
gem 'asciidoctor-pdf'
gem 'rouge'
EOF
bundle install
----

Run with

[source,bash]
----
bundle exec asciidoctor-pdf <filename>
----

=== Xilinx FPGA

==== ISE Webpack 14.7

You need the following packages:

* ncurses5-compat-libs (AUR)
* libstdc++5
* openmotif
* xorg-fonts-75dpi
* xorg-fonts-100dpi

The bundled EDK gcc compiler needs:

* lib32-glibc
* lib32-ncurses5-compat-libs (AUR)

Digilent USB-JTAG Drivers

* fxload (AUR)
* digilent.adept.runtime (AUR)
* digilent.adept.utilities (AUR)

Xilinx Platform Cable

* fxload (AUR)
* fxload-libusb (AUR)

=== PHP

You can run PHP as local development server with:

[source,bash]
----
php -S localhost:8000
----

==== Symfony

Install symfony and composer with

[source,bash]
----
sudo pacman -S composer
wget https://get.symfony.com/cli/installer -O - | bash
export PATH="$HOME/.symfony/bin:$PATH"
----

Activate the iconv plugin by creating the file `/etc/php/conf.d/00-iconv.ini` with the following content:

[source]
----
extension=iconv.so
----

===== Create an API framework

Go to your project root and type

[source,bash]
----
symfony new <project_name>
----

=== MariaDB

==== Enable MariaDB for PHP 7

Add `01-mysqli.ini` to `/etc/php/conf.d` with the following content:

[source]
----
extension=mysqli
----

==== Set root password like in older versions

Execute the following with `sudo mariadb`:

[source,sql]
----
ALTER USER root@localhost IDENTIFIED VIA mysql_native_password USING PASSWORD("verysecret")
----

=== Linux Kernel

==== Compile a new single intree-module

[source,bash]
----
cd <kernel-source>
make menuconfig
----

Select the module that was missing.

[source,bash]
----
make scripts prepare modules_prepare
make -C . M=drivers/<path to module>
----

Copy the module and update dependencies.

[source,bash]
----
sudo cp <path-to-module>/xyz.ko /lib/modules/<kernel-version>/<path-to-module>/
sudo depmod
----
