== System setup

=== Add user to a group

[source,bash]
----
usermod -aG <newgroup> <user>
newgrp <newgroup>
----

Last command adds the new group without the need to logout and back in.

=== Prevent PC speaker from beeping

[source,bash]
----
rmmod pcspkr
----

[source,bash]
----
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
----

=== Console environment

==== Set console font

Install `terminus-font`.

[source,bash]
----
setfont -v ter-112n
----

or use another from `/usr/share/kbd/consolefonts/`.

For system default use `/etc/default/console-setup`

[source,bash]
----
CHARMAP="UTF-8"
CODESET="Lat7"
FONTFACE="Terminus"
FONTSIZE="28x14"
----

=== E-Mail Setup

==== Mutt configuration

To use `mutt` as `imap` client, set the folder to the address:

----
set folder="imaps://username@mail.xxx"
set spoolfile = +INBOX
set postponed = +INBOX/Sent
set record = +INBOX/Sent
unset imap_passive
set imap_keepalive = 300
set mail_check = 60
----

Define the mailboxes manually

----
mailboxes +INBOX +INBOX/Sent <...>
----

Define the outgoing mail server

----
set smtp_url = "smtp://mail.blah.net"
set realname = "Your Name"
set from = "YourName@Mail.XXX"
set hostname = ""

unset ssl_verify_host
unset ssl_starttls
----

To add a signature, use

----
set signature = "~/.mutt/.signature"
----

To have the newest E-Mail on top, use

----
set sort_aux = reverse-date-received
----

For thread view, set

----
set sort = threads
----

Have nice colors with

[source,bash]
----
source "~/.mutt/colors.muttrc"
----

with the following content:

----
# vim: filetype=muttrc

# basic colors ---------------------------------------------------------
color normal        brightyellow    default
color error         red             default
color tilde         black           default
color message       cyan            default
color markers       red             white
color attachment    white           default
color search        brightmagenta   default
#color status        J_black         J_status
color status        brightyellow    black
color indicator     brightblack     yellow
color tree          yellow          default                                     # arrow in threads

# basic monocolor screen
mono  bold          bold
mono  underline     underline
mono  indicator     reverse
mono  error         bold

# index ----------------------------------------------------------------

color index         red             default         "~A"                        # all messages
color index         brightred       default         "~E"                        # expired messages
color index         blue            default         "~N"                        # new messages
color index         blue            default         "~O"                        # old messages
color index         brightmagenta   default         "~Q"                        # messages that have been replied to
color index         brightgreen     default         "~R"                        # read messages
color index         blue            default         "~U"                        # unread messages
color index         blue            default         "~U~$"                      # unread, unreferenced messages
color index         brightyellow    default         "~v"                        # messages part of a collapsed thread
color index         brightyellow    default         "~P"                        # messages from me
color index         cyan            default         "~p!~F"                     # messages to me
color index         cyan            default         "~N~p!~F"                   # new messages to me
color index         cyan            default         "~U~p!~F"                   # unread messages to me
color index         brightgreen     default         "~R~p!~F"                   # messages to me
color index         red             default         "~F"                        # flagged messages
color index         red             default         "~F~p"                      # flagged messages to me
color index         red             default         "~N~F"                      # new flagged messages
color index         red             default         "~N~F~p"                    # new flagged messages to me
color index         red             default         "~U~F~p"                    # new flagged messages to me
color index         black           red             "~D"                        # deleted messages
color index         brightcyan      default         "~v~(!~N)"                  # collapsed thread with no unread
color index         yellow          default         "~v~(~N)"                   # collapsed thread with some unread
color index         green           default         "~N~v~(~N)"                 # collapsed thread with unread parent
# statusbg used to indicated flagged when foreground color shows other status
# for collapsed thread
color index         red             black           "~v~(~F)!~N"                # collapsed thread with flagged, no unread
color index         yellow          black           "~v~(~F~N)"                 # collapsed thread with some unread & flagged
color index         green           black           "~N~v~(~F~N)"               # collapsed thread with unread parent & flagged
color index         green           black           "~N~v~(~F)"                 # collapsed thread with unread parent, no unread inside, but some flagged
color index         cyan            black           "~v~(~p)"                   # collapsed thread with unread parent, no unread inside, some to me directly
color index         yellow          red             "~v~(~D)"                   # thread with deleted (doesn't differentiate between all or partial)

# message headers ------------------------------------------------------

color hdrdefault    brightgreen     default
color header        brightyellow    default         "^(From)"
color header        blue            default         "^(Subject)"

# body -----------------------------------------------------------------

color quoted        blue            default
color quoted1       cyan            default
color quoted2       yellow          default
color quoted3       red             default
color quoted4       brightred       default

color signature     brightgreen     default
color bold          black           default
color underline     black           default
color normal        default         default
#
color body          brightcyan      default         "[;:][-o][)/(|]"    # emoticons
color body          brightcyan      default         "[;:][)(|]"         # emoticons
color body          brightcyan      default         "[*]?((N)?ACK|CU|LOL|SCNR|BRB|BTW|CWYL|\
                                                     |FWIW|vbg|GD&R|HTH|HTHBE|IMHO|IMNSHO|\
                                                     |IRL|RTFM|ROTFL|ROFL|YMMV)[*]?"
color body          brightcyan      default         "[ ][*][^*]*[*][ ]?" # more emoticon?
color body          brightcyan      default         "[ ]?[*][^*]*[*][ ]" # more emoticon?

## pgp

color body          red             default         "(BAD signature)"
color body          cyan            default         "(Good signature)"
color body          brightblack     default         "^gpg: Good signature .*"
color body          brightyellow    default         "^gpg: "
color body          brightyellow    red             "^gpg: BAD signature from.*"
mono  body          bold                            "^gpg: Good signature"
mono  body          bold                            "^gpg: BAD signature from.*"

# yes, an insance URL regex
color body          red             default         "([a-z][a-z0-9+-]*://(((([a-z0-9_.!~*'();:&=+$,-]|%[0-9a-f][0-9a-f])*@)?((([a-z0-9]([a-z0-9-]*[a-z0-9])?)\\.)*([a-z]([a-z0-9-]*[a-z0-9])?)\\.?|[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+)(:[0-9]+)?)|([a-z0-9_.!~*'()$,;:@&=+-]|%[0-9a-f][0-9a-f])+)(/([a-z0-9_.!~*'():@&=+$,-]|%[0-9a-f][0-9a-f])*(;([a-z0-9_.!~*'():@&=+$,-]|%[0-9a-f][0-9a-f])*)*(/([a-z0-9_.!~*'():@&=+$,-]|%[0-9a-f][0-9a-f])*(;([a-z0-9_.!~*'():@&=+$,-]|%[0-9a-f][0-9a-f])*)*)*)?(\\?([a-z0-9_.!~*'();/?:@&=+$,-]|%[0-9a-f][0-9a-f])*)?(#([a-z0-9_.!~*'();/?:@&=+$,-]|%[0-9a-f][0-9a-f])*)?|(www|ftp)\\.(([a-z0-9]([a-z0-9-]*[a-z0-9])?)\\.)*([a-z]([a-z0-9-]*[a-z0-9])?)\\.?(:[0-9]+)?(/([-a-z0-9_.!~*'():@&=+$,]|%[0-9a-f][0-9a-f])*(;([-a-z0-9_.!~*'():@&=+$,]|%[0-9a-f][0-9a-f])*)*(/([-a-z0-9_.!~*'():@&=+$,]|%[0-9a-f][0-9a-f])*(;([-a-z0-9_.!~*'():@&=+$,]|%[0-9a-f][0-9a-f])*)*)*)?(\\?([-a-z0-9_.!~*'();/?:@&=+$,]|%[0-9a-f][0-9a-f])*)?(#([-a-z0-9_.!~*'();/?:@&=+$,]|%[0-9a-f][0-9a-f])*)?)[^].,:;!)? \t\r\n<>\"]"
----

Some sidebar addons and key assignments

----
bind index G imap-fetch-mail

set sidebar_visible = yes
bind index,pager B sidebar-toggle-visible

bind index,pager \CP sidebar-prev
bind index,pager \CN sidebar-next
bind index,pager \CO sidebar-open

bind pager <up> previous-line
bind pager <down> next-line

set sidebar_delim_chars = "/"
----

=== X Environment

Install `Envy Code R` ttf font to `/usr/share/fonts/TTF`. Update font
cache with

[source,bash]
----
fc-cache -f -v
----

==== urxvt config

In `.Xresources` add

----
URxvt.font: xft:Envy Code R:style=regular:size=14
! URxvt.font: 9x15
URxvt*loginShell: true
URxvt*saveLines: 65535
URxvt*borderLess: false
URxvt*externalBorder: 1
URxvt*background: #000000
URxvt*foreground: #CCCCCC
URxvt*scrollBar: false
URxvt.resize-font.smaller: C-Down
URxvt.resize-font.bigger: C-Up
URxvt.perl-ext: default,url-select
URxvt.keysym.M-u: perl:url-select:select_next
URxvt.url-select.launcher: firefox
URxvt.url-select.underline: true
----

Make links clickable with (not with `urxvt-perls`!)

----
URxvt.perl-ext-common: default,matcher
URxvt.url-launcher: /usr/bin/xdg-open
URxvt.matcher.button: 1
----

Highlight:

----
URxvt.matcher.rend.0: Uline Bold fg5
----

Key-Shortcuts for URL list

----
URxvt.keysym.C-Delete: perl:matcher:last
URxvt.keysym.M-Delete: perl:matcher:list
----

Install `urxvt-perls`, which replaces the matcher above for mouse-less
selection with .

==== Graphical boot (plymouth)

* Clone and build `plymouth` (https://aur.archlinux.org/plymouth
* Re-generate initcpio

[source,bash]
----
sudo mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img -S autodetect
----

* Install display manager (`lxdm`)
* Enable `lxdm-plymouth.service`

Edit

* `/etc/lxdm/PostLogin`

[source,bash]
----
source ~/.xinitrc
----

* `/etc/plymouth/plymouthd.conf`

----
[Daemon]
Theme=...
ShowDelay=5
DeviceTimeout=5
----

* `/etc/mkinitcpio.conf`

[source,bash]
----
# Load i915 (or other graphics module) before any boot hooks
MODULES="i915"

...

HOOKS="base udev plymouth autodetect modconf keyboard keymap block plymouth-encrypt filesystems fsck"
----

Here, replace `encrypt` with `plymouth-encrypt` and load `plymouth`
after `udev`.

* Install `https://aur.archlinux.org/lxdm-themes`

From selected theme, edit `ui` files if needed.

=== Powerline

[source,bash]
----
pacman -S powerline-common  powerline-fonts
----

or

[source,bash]
----
pacaur -S python-powerline-git powerline-fonts-git tmux
----

`~/.bashrc`:

[source,bash]
----
[...]
if [ -f `which powerline-daemon` ]; then
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh
fi
----

_NOTE_ Use correct python version.

`~/.tmux.conf`

[source,bash]
----
source /usr/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
set-option -g default-terminal "screen-256color"
----

`~/.vimrc`

----
rtp+=$HOME/.local/lib/python3.5/site-packages/powerline/bindings/vim/
t_Co=256
----

=== Vim

==== Vim Vundle with some plugins

----
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
----

In your `.vimrc`:

----
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vundleplugs')

Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

call vundle#end()
----

==== Highlight extra whitespaces

----
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
----

==== Smart Indentation

----
set smartindent
----

==== F2 for paste mode

----
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
----

==== Misc Default settings

----
set syntax on

set number

set tabstop=8
set shiftwidth=8
set softtabstop=8
set smarttab
set noexpandtab

set encoding=utf-8
set fileencoding=utf-8

set nofoldenable

set laststatus=2

et showbreak=↲\
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:\ ,extends:⟩,precedes:⟨
set list

set t_Co=256
----

=== vsftpd

in `/etc/vsftpd.conf`, set

----
seccomp_sandbox=NO
----

_NOTE_: This is needed due to a bug related to kernels `v4.18+`, which
prevents working of directory listings.


