== System setup

=== Add user to a group

[source,bash]
----
usermod -aG <newgroup> <user>
newgrp <newgroup>
----

Last command adds the new group without the need to logout and back in.

=== Prevent PC speaker from beeping

[source,bash]
----
rmmod pcspkr
----

[source,bash]
----
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
----

=== Console environment

==== Set console font

Install `terminus-font`.

[source,bash]
----
setfont -v ter-112n
----

or use another from `/usr/share/kbd/consolefonts/`.

For system default use `/etc/default/console-setup`

[source,bash]
----
CHARMAP="UTF-8"
CODESET="Lat7"
FONTFACE="Terminus"
FONTSIZE="28x14"
----

=== E-Mail Setup

include::mutt.adoc[]

=== X Environment

Install `Envy Code R` ttf font to `/usr/share/fonts/TTF`. Update font
cache with

[source,bash]
----
fc-cache -f -v
----

==== urxvt config

In `.Xresources` add

----
URxvt.font: xft:Envy Code R:style=regular:size=14
! URxvt.font: 9x15
URxvt*loginShell: true
URxvt*saveLines: 65535
URxvt*borderLess: false
URxvt*externalBorder: 1
URxvt*background: #000000
URxvt*foreground: #CCCCCC
URxvt*scrollBar: false
URxvt.resize-font.smaller: C-Down
URxvt.resize-font.bigger: C-Up
URxvt.perl-ext: default,url-select
URxvt.keysym.M-u: perl:url-select:select_next
URxvt.url-select.launcher: firefox
URxvt.url-select.underline: true
----

Make links clickable with (not with `urxvt-perls`!)

----
URxvt.perl-ext-common: default,matcher
URxvt.url-launcher: /usr/bin/xdg-open
URxvt.matcher.button: 1
----

Highlight:

----
URxvt.matcher.rend.0: Uline Bold fg5
----

Key-Shortcuts for URL list

----
URxvt.keysym.C-Delete: perl:matcher:last
URxvt.keysym.M-Delete: perl:matcher:list
----

Install `urxvt-perls`, which replaces the matcher above for mouse-less
selection with .

==== Graphical boot (plymouth)

* Clone and build `plymouth` (https://aur.archlinux.org/plymouth
* Re-generate initcpio

[source,bash]
----
sudo mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img -S autodetect
----

* Install display manager (`lxdm`)
* Enable `lxdm-plymouth.service`

Edit

* `/etc/lxdm/PostLogin`

[source,bash]
----
source ~/.xinitrc
----

* `/etc/plymouth/plymouthd.conf`

----
[Daemon]
Theme=...
ShowDelay=5
DeviceTimeout=5
----

* `/etc/mkinitcpio.conf`

[source,bash]
----
# Load i915 (or other graphics module) before any boot hooks
MODULES="i915"

...

HOOKS="base udev plymouth autodetect modconf keyboard keymap block plymouth-encrypt filesystems fsck"
----

Here, replace `encrypt` with `plymouth-encrypt` and load `plymouth`
after `udev`.

* Install `https://aur.archlinux.org/lxdm-themes`

From selected theme, edit `ui` files if needed.

=== Powerline

[source,bash]
----
pacman -S powerline-common  powerline-fonts
----

or

[source,bash]
----
pacaur -S python-powerline-git powerline-fonts-git tmux
----

`~/.bashrc`:

[source,bash]
----
[...]
if [ -f `which powerline-daemon` ]; then
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh
fi
----

_NOTE_ Use correct python version.

`~/.tmux.conf`

[source,bash]
----
source /usr/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
set-option -g default-terminal "screen-256color"
----

`~/.vimrc`

----
rtp+=$HOME/.local/lib/python3.5/site-packages/powerline/bindings/vim/
t_Co=256
----

=== Vim

==== Vim Vundle with some plugins

----
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
----

In your `.vimrc`:

----
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vundleplugs')

Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

call vundle#end()
----

==== Highlight extra whitespaces

----
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
----

==== Smart Indentation

----
set smartindent
----

==== F2 for paste mode

----
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
----

==== Misc Default settings

----
set syntax on

set number

set tabstop=8
set shiftwidth=8
set softtabstop=8
set smarttab
set noexpandtab

set encoding=utf-8
set fileencoding=utf-8

set nofoldenable

set laststatus=2

et showbreak=↲\
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:\ ,extends:⟩,precedes:⟨
set list

set t_Co=256
----

=== vsftpd

in `/etc/vsftpd.conf`, set

----
seccomp_sandbox=NO
----

_NOTE_: This is needed due to a bug related to kernels `v4.18+`, which
prevents working of directory listings.


