= Linux Tips and Tricks
Andreas Reichel
:numbered:
:doctype: book
:sectnums:
:toclevels: 5
:sectnumlevels: 5
:toc:

== Booting

=== EFI Partition

A bootable EFI system needs an ESP partition. This is easily created
with `parted`. Just make a FAT32 partition, and use toggle:

....
toggle <partnum> ESP
....

For different architectures, there exit standard boot file names:

* `x64`: `/EFI/BOOT/BOOTX64.EFI`
* `386`: `/EFI/BOOT/BOOTIA32.EFI`
* `IA64`: `/EFI/BOOT/BOOTIA64.EFI`

=== Installing GRUB

=== Removeable disk

To install grub to create a bootable USB stick, just use

....
sudo grub-install --target x86_64-efi --efi-directory=/mnt --boot-directory=/mnt/boot --removable
....

Here, grub is installed to `/boot/grub`, whereas the EFI file resides in
`EFI/BOOT/` on the same partition, which is mounted to `/mnt`.

Now grub has an internal configuration file, that tells it where to load
the `grub.cfg` from. For USB-Sticks this is too complicated. Just create
a working `grub.cfg` and include needed modules into `grub`:

....
grub-mkimage -c grub.cfg -O x86_64-efi -p /boot/grub -o bootx64.efi disk part_gpt fat linux normal search search_fs_uuid
....

Then overwrite the existing `/EFI/BOOT/BOOTX64.EFI` with the just
generated one.

Here is an example `grub.cfg`:

....
insmod ext2
insmod efi_uga
insmod efi_gop
insmod font

search --no-floppy --fs-uuid --set=root <fs-uuid for root>
linux /boot/vmlinuz-linux root=UUID=<fs-uuid for root> rootwait console=tty0 console=ttyS0,115200 vga=text
initrd /boot/initramfs-linux.img
boot
....

_NOTE_: This does not have a grub menu, it just boots a kernel.

== Console

=== No access to pty for tool

If a tool cannot open a pseudo terminal, use

....
screen /dev/null
....

_NOTE_: It is not good to alter the file access rights for the dev node
since this would allow access to your terminal.

== Filesystem

=== Managing disk space

To clean up your harddrive, use `ncdu`. It is faster than `filelight`.

=== To many files

If for example `rm` refuses to delete files, because `*` cannot be
expanded since the argument list would get too log, you can use `find`:

....
find /path/to/dir -delete
....

If you don’t want that `/path/to/dir` itself is also removed, use

....
find /path/to/dir -type f -delete
....

=== Handling multi-partition disk images

==== kpartx

....
git clone https://aur.archlinux.org/multipath-tools.git
....

==== Access DOS-drives inside images with mcopy (mtools)

You can assign a drive letter with an image file with `~/.mtoolsrc`

....
drive c: file="<path-to-image>"
....

Copy `file` from current directory into the drive assigned with the
partition at `offset` inside `disk.img`:

....
mcopy -i disk.img@@offset file ::/
....

You can get the offset with `fdisk -l disk.img` and multiply `Start`
with `512`.

....
fdisk -l disk.img | grep 'img1' | awk '{print $3*512}'
....

==== Information about dos drive

....
minfo -i disk.img@@offset
....

== GUI

=== Gnome configuration

....
dconf dump /
....

=== Disable auto-mounter

This feature is probably configured by a gsettings schema. You can use

....
gsettings list-schemas
....

to get an overview.

==== Disable auto-mounter for mate/caja

....
gsettings set org.mate.media-handling automount false
....

==== Disable auto-mounter for gnome

....
gsettings set org.gnome.desktop.media-handling automount false
....

== Documentation

=== Markdown

==== WYSIWYG editor

Use `retext`.

=== Ascii Doctor

Install `asciidoctor` and continue reading <<asciidoc_ruby>>.

== System setup

=== Add user to a group

....
sudo usermod -aG <newgroup> <user>
newgrp <newgroup>
....

Last command adds the new group without the need to logout and back in.

=== Prevent PC speaker from beeping

....
$ sudo rmmod pcspkr
....

....
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
....

=== Console environment

==== Set console font

Install `terminus-font`.

....
setfont -v ter-112n
....

or use another from `/usr/share/kbd/consolefonts/`.

For system default use `/etc/default/console-setup`

....
CHARMAP="UTF-8"
CODESET="Lat7"
FONTFACE="Terminus"
FONTSIZE="28x14"
....

=== X Environment

Install `Envy Code R` ttf font to `/usr/share/fonts/TTF`. Update font
cache with

....
fc-cache -f -v
....

==== urxvt config

In `.Xresources` add

....
URxvt.font: xft:Envy Code R:style=regular:size=14
! URxvt.font: 9x15
URxvt*loginShell: true
URxvt*saveLines: 65535
URxvt*borderLess: false
URxvt*externalBorder: 1
URxvt*background: #000000
URxvt*foreground: #CCCCCC
URxvt*scrollBar: false
URxvt.resize-font.smaller: C-Down
URxvt.resize-font.bigger: C-Up
URxvt.perl-ext: default,url-select
URxvt.keysym.M-u: perl:url-select:select_next
URxvt.url-select.launcher: firefox
URxvt.url-select.underline: true
....

Make links clickable with (not with `urxvt-perls`!)

....
URxvt.perl-ext-common: default,matcher
URxvt.url-launcher: /usr/bin/xdg-open
URxvt.matcher.button: 1
....

Highlight:

....
URxvt.matcher.rend.0: Uline Bold fg5
....

Key-Shortcuts for URL list

....
URxvt.keysym.C-Delete: perl:matcher:last
URxvt.keysym.M-Delete: perl:matcher:list
....

Install `urxvt-perls`, which replaces the matcher above for mouse-less
selection with .

==== Graphical boot (plymouth)

* Clone and build `plymouth` (https://aur.archlinux.org/plymouth
* Re-generate initcpio

....
sudo mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img -S autodetect
....

* Install display manager (`lxdm`)
* Enable `lxdm-plymouth.service`

Edit

* `/etc/lxdm/PostLogin`

....
source ~/.xinitrc
....

* `/etc/plymouth/plymouthd.conf`

....
[Daemon]
Theme=...
ShowDelay=5
DeviceTimeout=5
....

* `/etc/mkinitcpio.conf`

....
# Load i915 (or other graphics module) before any boot hooks
MODULES="i915"

...

HOOKS="base udev plymouth autodetect modconf keyboard keymap block plymouth-encrypt filesystems fsck"
....

Here, replace `encrypt` with `plymouth-encrypt` and load `plymouth`
after `udev`.

* Install `https://aur.archlinux.org/lxdm-themes`

From selected theme, edit `ui` files if needed.

=== Powerline

....
pacman -S powerline-common  powerline-fonts
....

or

....
pacaur -S python-powerline-git powerline-fonts-git tmux
....

`~/.bashrc`:

....
[...]
if [ -f `which powerline-daemon` ]; then
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/lib/python3.5/site-packages/powerline/bindings/bash/powerline.sh
fi
....

_NOTE_ Use correct python version.

`~/.tmux.conf`

....
source /usr/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
set-option -g default-terminal "screen-256color"
....

`~/.vimrc`

....
rtp+=$HOME/.local/lib/python3.5/site-packages/powerline/bindings/vim/
t_Co=256
....

=== Vim

==== Vim Vundle with some plugins

....
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
....

In your `.vimrc`:

....
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vundleplugs')

Plugin 'VundleVim/Vundle.vim'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

call vundle#end()
....

==== Highlight extra whitespaces

....
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
....

==== Smart Indentation

....
set smartindent
....

==== F2 for paste mode

....
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode
....

==== Misc Default settings

....
set syntax on

set number

set tabstop=8
set shiftwidth=8
set softtabstop=8
set smarttab
set noexpandtab

set encoding=utf-8
set fileencoding=utf-8

set nofoldenable

set laststatus=2

et showbreak=↲\
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:\ ,extends:⟩,precedes:⟨
set list

set t_Co=256
....

=== vsftpd

in `/etc/vsftpd.conf`, set

....
seccomp_sandbox=NO
....

_NOTE_: This is needed due to a bug related to kernels `v4.18+`, which
prevents working of directory listings.

== System Maintenance

=== pacman

==== Remove package disregarding dependencies

....
pacman -Rdd <package>
....

== Development

=== Versioning

==== Git

===== Merge a branch

Never merge abranch and allow non-fast-forwarding!

Always use:

....
git merge --ff-only <branch>
....

===== Change merge-commit to normal commit

The only difference between a merge commit and a normal commit is that a
merge commit has two parents. Use

....
git replace --edit <COMMIT SHA>
....

Afterwards, only the `view` of the commit graph is altered, not the
commits on the branch themselves. To reify this, use

....
git filter-branch -- --all
....

===== Change author of commit

....
git rebase -i <SHA to change>
....

Mark commit as `edit`.

Use

....
git commit --amend --reset-author
....

=== C/C++

==== Order of object files in static library

The order does not matter. Just package all object files with

```
ar rcv output.a file1.o file2.o file3.o
```

This is interesting, because we don't need the dependency file generation by the compiler then.

==== Build kernel

Build it out of tree! From within the build-directory, use

....
make -C <path-to-source> O=$(pwd) <target>
....

==== autotools

New Project with autotools

* install `autotools`
* install `automake

Create project directory tree. Create source files.

....
autoscan
....

Rename `configure.scan` to `configure.ac`. Edit `configure.ac`
(`AC_INIT` line).

Write `Makefile.am` (one or more). Edit `configure.ac` and add
`AM_INIT_AUTOMAKE`.

Then in `lib/Makefile.am`:

* If you don’t want to install a lib, use `noinst_LIBRARIES`
* static libs need `RANLIB`, so add `AC_PROG_RANLIB` into the
`configure.ac`
* Do not use `CFLAGS` and `LDFLAGS`, but `AM_CFLAGS` and `AM_LDFLAGS`.

==== Cross-Compilation

Build cross-compiler from `aur` needs the following steps:

* Have native: `elfutils`, `gperf`

Build in the following order:

1.  binutils
2.  gcc-stage1
3.  linux-api-headers
4.  glibc-headers
5.  gcc-stage2 (removes stage1)
6.  glibc (removes glibc-headers)
7.  gcc (removes stage2)

=== Python

Interesting modules:

* `Requests` - http lib
* `Scrapy` - webscraping
* `wxPython` - GUI
* `Pillow` - imaging lib
* `SQLAlchemy` - database lib
* `BeautifulSoup` - xml and html parser
* `Twisted` - network app dev
* `NumPy` - Advanced maths
* `SciPy` - algorithms and mathematical tools for science
* `matplotlib` - data plotting
* `Pygame` - 2d game dev
* `Pyglet` - 3d and multimedia framework
* `pyQT` - GUI
* `pyGtk` - GUI
* `Scapy` - packet sniffer and analyzer
* `pywin32` - for windows b’’h
* `nltk` - natural language toolkig
* `nose` - testing framework
* `SymPy` - symbolic maths
* `IPython` - prompt with extras

=== Ruby

==== Local gems for `bundle` and `gem`

You can use the `--path` option to `bundle` for project dependent gems directory, or you
can globally configure a user-gems directory for all user projects:

```
bundle config path "~/.gem"
```

[[asciidoc_ruby]]
===== asciidoctor-pdf

```
bundle init
cat <<EOF > Gemfile
gem 'asciidoctor-pdf'
gem 'rouge'
EOF
bundle install
```

Run with

```
bundle exec asciidoctor-pdf <filename>
```

== Virtualization

=== Docker

==== Not allowed to talk to docker daemon

Add user to `docker` group.

==== Mount into container

....
docker run -v /path/on/host:/path/in/container
....

_NOTE_: Relative paths are not allowed.

==== Verify environment

....
sudo systemctl show --property Environment docker
....

==== Proxy configuration for docker

Both docker daemon and container need a proxy configuration. Easiest way
is to use a `.docker/config.json`:

....
{
"proxies": {
        "default": {
            "httpProxy": "http://ip:port"
            "httpsProxy": "http://ip:port"
            "noProxy": ".domain.d,.domainB.c,ip"
        }
    }
}
....

Other ways are

`/etc/systemd/system/docker.service.d/http-proxy.conf`:

....
[Service]
Environment="HTTP_PROXY=http://ip:port"
Environment="HTTPS_PROXY=http://ip:port"
Environment="FTP_PROXY=..."
Environment=NO_PROXY=..."
....

and command-line parameters

....
docker run -e "http_proxy=..." -e "https_proxy=..." ...
....
