== Virtualization

=== qemu

==== Test an UEFI bootable memory stick with qemu

[source,bash]
----
qemu-system-x86_64 --bios /usr/share/ovmf/x64/OVMF_CODE.fd -m 4G -usb -device nec-usb-xhci -usb -device usb-host,vendorid=0x0951,productid=0x1666
----

This forwards the USB device with specified product and vendor ID to qemu, where the firmware tries to boot from it.

=== systemd-nspawn

==== unit to spawn container

Enable machines.target

[source,bash]
----
systemctl enable machines.target
----

Create service

[source,bash]
----
systemctl enable systemd-nspawn@myContainer.service
----

Customize startup with `/etc/systemd/nspawn/myContainer.nspawn`.

_NOTE_: Per default, user namespace is activated and `GID`s and `UID`s of
all files in the container get changed on first startup to a random value.
This messes with the file system. If you do not want this, use the following within the nspawn file:

----
[Exec]
PrivateUser=no
----

For the sake of explicitness, I use

----
[Exec]
Boot=yes
PrivateUsers=no

[Network]
VirtualEthernet=yes
----

=== Docker

==== Not allowed to talk to docker daemon

Add user to `docker` group.

==== Mount into container

[source,bash]
----
docker run -v /path/on/host:/path/in/container
----

_NOTE_: Relative paths are not allowed.

==== Verify environment

[source,bash]
----
sudo systemctl show --property Environment docker
----

==== Proxy configuration for docker

Both docker daemon and container need a proxy configuration. Easiest way
is to use a `.docker/config.json`:

[source,json]
----
{
"proxies": {
        "default": {
            "httpProxy": "http://ip:port"
            "httpsProxy": "http://ip:port"
            "noProxy": ".domain.d,.domainB.c,ip"
        }
    }
}
----

Other ways are

`/etc/systemd/system/docker.service.d/http-proxy.conf`:

[source,systemd]
----
[Service]
Environment="HTTP_PROXY=http://ip:port"
Environment="HTTPS_PROXY=http://ip:port"
Environment="FTP_PROXY=..."
Environment=NO_PROXY=..."
----

and command-line parameters

[source,bash]
----
docker run -e "http_proxy=..." -e "https_proxy=..." ...
----

=== runc

==== systemd files to start container

Service file `<containername>.service`:

[source,systemd]
----
[Service]
Type=simple
WorkingDirectory=/opt/runc/<containername>
ExecStart=/usr/local/sbin/runc run -d --pid-file /run/runc_<containername>.pid <containername>
ExecStop=/usr/local/sbin/runc kill <containername> KILL
ExecStopPost=/usr/local/sbin/runc delete <containername>
PIDFile=/run/runc_<containername>.pid

[Install]
WantedBy=multi-user.target
----

Target file `<containername>.target` (optional):

[source,systemd]
----
[Unit]
Description=Blurb blurb
Requires=<containername>.service

[Install]
WantedBy=multi-user.target
----

=== Vagrant

==== Configure proxy in vagrant file

Install the `vagrant-proxyconf` plugin:

[source,bash]
----
vagrant plugin install vagrant-proxyconf
----

Add the following to your `Vagrantfile` according to your needs:

[source]
----
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://192.168.0.2:3128/"
    config.proxy.https    = "http://192.168.0.2:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
  # ... other stuff
end
----

=== Mount .vdi images

Use `qemu-nbd` with kernel module `nbd` loaded:

```bash
qemu-nbd -c /dev/nbd0 image.vdi
```

then mount the needed partition `/dev/nbd0pX`.
Afterwards, unmount and disconnect with

```bash
qemu-nbd -d /dev/nbd0
```


=== VirtualBox in Windows

To make VMs available for all users, set the environment variable
`VBOX_USER_HOME`.

=== VirtualBox reset hard disk UUID

When importing a hard disk image, the `UUID` might mismatch and Virtualbox
might refues to start. To fix this, issue the command


```bash
VBoxManage internalcommands sethduuid <imagefile> <newUUID>
```
