== Xorg

Config snippets reside in `/etc/X11/xorg.conf.d/`, for example `10-keyboard.conf`.

=== Autostart X on login

You can autostart X from `.bash_profile` or `.bashrc` or alike:

[source,bash]
----
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	exec startx
fi
----

=== Enable external monitor or change resolution

Use `arandr`.

=== Cannot connect to server

Try `xhost +` to allow connections from everyone.
Access can later be restricted to a whitelist again with `xhost -`.

Additional access control list is `/etc/Xn.hosts` with display number
`n`. It contains entries a la `family:name`. See the man page `XHOST(1)`.

=== X forwarding via `ssh`

On the server, enable `X11Forwarding yes` in `/etc/ssh/sshd_config`.
On the client, use `ssh -X`. The program `xauth` must be present on the server. `ssh` automatically sets `XAUTHORITY` and `DISPLAY` environment variables.

=== Keyboard layout switching

XOrg config snippet:

----
Section "InputClass"
	Identifier	"Keyboard Defaults"
	MatchIsKeyboard	"yes"
	Option "XkbLayout" "us,de"
	Option "XkbVariant" "altgr-intl"
	Option "XkbOptions" "grp:alt_shift_toggle"
EndSection
----

Layout switching can also be achieved with `setxkbmap`.

[source,bash]
----
setxkbmap -rules xorg -model pc104 -laout us -option ""
----

or

[source,bash]
----
setxkbmap -rules xorg -model logicordless -layout "us,cz,de" \
          -option "grp:alt_shift_toggle"
----

=== Tap to click on touch pads

XOrg config snippet:

----
Section "InputClass"
	Identifier	"libinput touchpad catchall"
	MatchIsTouchpad "on"
	MatchDevicePath "/dev/input/event*"
	Driver		"libinput"
	Option		"Tapping" "on"
EndSection
----

*Note*: On the MSI GE63 this led to right click by tapping with two fingers and
middle button by tapping with three fingers.

=== Snow on windows

Start `xsnow`.

=== Optimus chipsets and switching GPU

`bumblebee` is deprecated, do not use it.
Host CPU is Intel with integrated GPU, dedicated card is `nouveau`.

Install `nouveau` driver for NVidia cards. Have sections in `xorg.conf` for devices, screens and displays.

----
Section "Device"
	Identifier "intel"
	Driver	"intel"
	VendorName "Intel Corporation"
	BusID "PCI:0:2:0"
EndSection

Section "Device"
	Identifier "nouveau"
	Driver	"nouveau"
	VendorName "NVIDIA Corporation"
	BusID "PCI:3:0:0"
EndSection
----
Retrieve the needed bus numbers with `lspci`. For example `00:02.0` becomes `PCI:0:2:0`.

For my Dell laptop:

----
Section "Monitor"
	Identifier "Monitor0"
	VendorName "Unknown"
	ModelName "Unknown"
	Option "DPMS"
	Modeline "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync
	Option "PreferredMode" "1920x1080_60.00"
EndSection
----

----
Section "Screen"
	Identifier "intel"
	Device "intel"
	Monitor "Monitor0"
	DefaultDepth 24
	SubSection "Display"
		Depth 24
		Modes "1920x1080_60.00"
	EndSubSection
EndSection
----

Now prefix any application with `DRI_PRIME=0` or `DRI_PRIME=1` to run it on one of the GPUs.

*Example*:

[source,bash]
----
DRI_PRIME=1 glxinfo | grep "OpenGL renderer"
OpenGL renderer string: NV118

DRI_PRIME=0 glxinfo | grep "OpenGL renderer"
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
----

=== Composite manager

Use `compton`. It is a fork from a fork from `xcompmgr`.

[source,bash]
----
pacman -S compton
----

The configuration file is `/etc/xdg/compton.conf`.

Autostart it with your `.xinitrc` for example.

[source,bash]
----
compton -b -d :0
----

`-b` starts in background mode and `-d :0` starts it on all monitors belonging to display `:0`.

==== Transparency for special window class

For example to make all `urxvt` windows transparent, add the following to

`/etc/xdg/compton.conf`:

----
opacity-rule = [ "85:class_g = 'URxvt'" ]
----
